services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_app_container
    restart: unless-stopped
    # ports:
    #   - 3000:3000 If you expose port 3000 ➡ users can bypass Nginx and access Express dirctly. which defeats the purpose the purpose of the reverse proxy.
    environment:
      NODE_ENV: production
      DB_HOST: db # Tells our app to connect to the database service named `db` (the postgres container).
      DB_PORT: 5432 # The default Postgres port, our app uses to know which port to connect to on the `db` service.
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    container_name: my_db_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy_container
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # mounting your nginx.conf file into the Nginx container at /etc/nginx/nginx.conf ➡ This lets you fully control Nginx’s configuration
    depends_on:
      - app

volumes:
  db_data:
